/* @flow */

export const ERROR_CODE = {
    VALIDATION_ERROR: ('validation_error' : 'validation_error'),
    PAYMENT_SOURCE_INFO_CANNOT_BE_VERIFIED:('PAYMENT_SOURCE_INFO_CANNOT_BE_VERIFIED':'PAYMENT_SOURCE_INFO_CANNOT_BE_VERIFIED'),
    PAYMENT_SOURCE_DECLINED_BY_PROCESSOR:('PAYMENT_SOURCE_DECLINED_BY_PROCESSOR','PAYMENT_SOURCE_DECLINED_BY_PROCESSOR')
};
