export const FPTI_KEY = {
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 5f5a6a6 (simplify the code)
  FEED: "feed_name",
  STATE: "state_name",
  EVENT_NAME: "event_name",
  TRANSITION: "transition_name",
  PAGE: "page_name",
  BUTTON_TYPE: "button_type",
  SESSION_UID: "page_session_id",
  BUTTON_SESSION_UID: "button_session_id",
  TOKEN: "token",
  CONTEXT_ID: "context_id",
  CONTEXT_TYPE: "context_type",
  REFERER: "referer_url",
  MERCHANT_DOMAIN: "merchant_domain",
  PAY_ID: "pay_id",
  SELLER_ID: "seller_id",
  CLIENT_ID: "client_id",
  DATA_SOURCE: "serverside_data_source",
  BUTTON_SOURCE: "button_source",
  ERROR_CODE: "ext_error_code",
  ERROR_DESC: "ext_error_desc",
  PAGE_LOAD_TIME: "page_load_time",
  EXPERIMENT_NAME: "pxp_exp_id",
  TREATMENT_NAME: "pxp_trtmnt_id",
  TRANSITION_TIME: "transition_time",
  FUNDING_LIST: "eligible_payment_methods",
  FUNDING_COUNT: "eligible_payment_count",
  CHOSEN_FUNDING: "selected_payment_method",
  BUTTON_LAYOUT: "button_layout",
  VERSION: "checkoutjs_version",
  LOCALE: "locale",
  BUYER_COUNTRY: "buyer_cntry",
  INTEGRATION_IDENTIFIER: "integration_identifier",
  PARTNER_ATTRIBUTION_ID: "bn_code",
  PAGE_TYPE: "pp_placement",
  SDK_NAME: "sdk_name",
  SDK_VERSION: "sdk_version",
  SDK_ENVIRONMENT: "sdk_environment",
  MOBILE_APP_VERSION: "mobile_app_version",
  MOBILE_BUNDLE_IDENTIFIER: "mapv",
  USER_AGENT: "user_agent",
  USER_ACTION: "user_action",
  CONTEXT_CORRID: "context_correlation_id",
  SDK_CACHE: "sdk_cache",
  SDK_LOAD_TIME: "sdk_load_time",
  IS_VAULT: "is_vault",
  DISABLE_FUNDING: "disable_funding",
  DISABLE_CARD: "disable_card",
  RESPONSE_DURATION: "response_duration",
  SDK_INTEGRATION_SOURCE: "sdk_integration_source",
  PAYMENT_FLOW: "payment_flow",
  BUTTON_VERSION: "button_version",
  FI_LIST: "fi_list",
  CHOSEN_FI_TYPE: "chosen_fi_type",
  SELECTED_FI: "merchant_selected_funding_source",
  POTENTIAL_PAYMENT_METHODS: "potential_payment_methods",
  PAY_NOW: "pay_now",
  STICKINESS_ID: "stickiness_id",
  TIMESTAMP: "t",
  OPTION_SELECTED: "optsel",
  USER_IDENTITY_METHOD: "user_identity_method",
  FIELDS_COMPONENT_SESSION_ID: "fields_component_session_id",
  CPL_COMP_METRICS: "cpl_comp_metrics",
  CPL_CHUNK_METRICS: "cpl_chunk_metrics",
  CPL_QUERY_METRICS: "cpl_query_metrics",
} as const;
<<<<<<< HEAD
export const FPTI_USER_ACTION = {
  COMMIT: "commit",
  CONTINUE: "continue",
} as const;
export const FPTI_DATA_SOURCE = {
  PAYMENTS_SDK: "checkout",
} as const;
export const FPTI_FEED = {
  PAYMENTS_SDK: "payments_sdk",
} as const;
export const FPTI_SDK_NAME = {
  PAYMENTS_SDK: "payments_sdk",
} as const;
=======
  FEED: "feed_name" as const,
  STATE: "state_name" as const,
  EVENT_NAME: "event_name" as const,
  TRANSITION: "transition_name" as const,
  PAGE: "page_name" as const,
  BUTTON_TYPE: "button_type" as const,
  SESSION_UID: "page_session_id" as const,
  BUTTON_SESSION_UID: "button_session_id" as const,
  TOKEN: "token" as const,
  CONTEXT_ID: "context_id" as const,
  CONTEXT_TYPE: "context_type" as const,
  REFERER: "referer_url" as const,
  MERCHANT_DOMAIN: "merchant_domain" as const,
  PAY_ID: "pay_id" as const,
  SELLER_ID: "seller_id" as const,
  CLIENT_ID: "client_id" as const,
  DATA_SOURCE: "serverside_data_source" as const,
  BUTTON_SOURCE: "button_source" as const,
  ERROR_CODE: "ext_error_code" as const,
  ERROR_DESC: "ext_error_desc" as const,
  PAGE_LOAD_TIME: "page_load_time" as const,
  EXPERIMENT_NAME: "pxp_exp_id" as const,
  TREATMENT_NAME: "pxp_trtmnt_id" as const,
  TRANSITION_TIME: "transition_time" as const,
  FUNDING_LIST: "eligible_payment_methods" as const,
  FUNDING_COUNT: "eligible_payment_count" as const,
  CHOSEN_FUNDING: "selected_payment_method" as const,
  BUTTON_LAYOUT: "button_layout" as const,
  VERSION: "checkoutjs_version" as const,
  LOCALE: "locale" as const,
  BUYER_COUNTRY: "buyer_cntry" as const,
  INTEGRATION_IDENTIFIER: "integration_identifier" as const,
  PARTNER_ATTRIBUTION_ID: "bn_code" as const,
  PAGE_TYPE: "pp_placement" as const,
  SDK_NAME: "sdk_name" as const,
  SDK_VERSION: "sdk_version" as const,
  SDK_ENVIRONMENT: "sdk_environment" as const,
  MOBILE_APP_VERSION: "mobile_app_version" as const,
  MOBILE_BUNDLE_IDENTIFIER: "mapv" as const,
  USER_AGENT: "user_agent" as const,
  USER_ACTION: "user_action" as const,
  CONTEXT_CORRID: "context_correlation_id" as const,
  SDK_CACHE: "sdk_cache" as const,
  SDK_LOAD_TIME: "sdk_load_time" as const,
  IS_VAULT: "is_vault" as const,
  DISABLE_FUNDING: "disable_funding" as const,
  DISABLE_CARD: "disable_card" as const,
  RESPONSE_DURATION: "response_duration" as const,
  SDK_INTEGRATION_SOURCE: "sdk_integration_source" as const,
  PAYMENT_FLOW: "payment_flow" as const,
  BUTTON_VERSION: "button_version" as const,
  FI_LIST: "fi_list" as const,
  CHOSEN_FI_TYPE: "chosen_fi_type" as const,
  SELECTED_FI: "merchant_selected_funding_source" as const,
  POTENTIAL_PAYMENT_METHODS: "potential_payment_methods" as const,
  PAY_NOW: "pay_now" as const,
  STICKINESS_ID: "stickiness_id" as const,
  TIMESTAMP: "t" as const,
  OPTION_SELECTED: "optsel" as const,
  USER_IDENTITY_METHOD: "user_identity_method" as const,
  FIELDS_COMPONENT_SESSION_ID: "fields_component_session_id" as const,
  CPL_COMP_METRICS: "cpl_comp_metrics" as const,
  CPL_CHUNK_METRICS: "cpl_chunk_metrics" as const,
  CPL_QUERY_METRICS: "cpl_query_metrics" as const,
};
=======
>>>>>>> 5f5a6a6 (simplify the code)
export const FPTI_USER_ACTION = {
  COMMIT: "commit",
  CONTINUE: "continue",
} as const;
export const FPTI_DATA_SOURCE = {
  PAYMENTS_SDK: "checkout",
} as const;
export const FPTI_FEED = {
  PAYMENTS_SDK: "payments_sdk",
} as const;
export const FPTI_SDK_NAME = {
<<<<<<< HEAD
  PAYMENTS_SDK: "payments_sdk" as const,
};
>>>>>>> b2acffc (feat!: ts-migration)
=======
  PAYMENTS_SDK: "payments_sdk",
} as const;
>>>>>>> 5f5a6a6 (simplify the code)
