export const FUNDING = {
  PAYPAL: "paypal",
  VENMO: "venmo",
  APPLEPAY: "applepay",
  ITAU: "itau",
  CREDIT: "credit",
  PAYLATER: "paylater",
  CARD: "card",
  IDEAL: "ideal",
  SEPA: "sepa",
  BANCONTACT: "bancontact",
  GIROPAY: "giropay",
  SOFORT: "sofort",
  EPS: "eps",
  MYBANK: "mybank",
  P24: "p24",
  VERKKOPANKKI: "verkkopankki",
  PAYU: "payu",
  BLIK: "blik",
  TRUSTLY: "trustly",
  ZIMPLER: "zimpler",
  MAXIMA: "maxima",
  OXXO: "oxxo",
  BOLETO: "boleto",
  BOLETOBANCARIO: "boletobancario",
  WECHATPAY: "wechatpay",
  MERCADOPAGO: "mercadopago",
  MULTIBANCO: "multibanco",
  SATISPAY: "satispay",
  PAIDY: "paidy",
} as const;
export const FUNDING_BRAND_LABEL = {
  PAYPAL: "PayPal",
  CREDIT: "PayPal Credit",
} as const;
export const CARD = {
  VISA: "visa",
  MASTERCARD: "mastercard",
  AMEX: "amex",
  DISCOVER: "discover",
  HIPER: "hiper",
  ELO: "elo",
  JCB: "jcb",
  CUP: "cup",
} as const;
export const WALLET_INSTRUMENT = {
  BALANCE: "balance",
  CARD: "card",
  BANK: "bank",
  CREDIT: "credit",
} as const;
export const FUNDING_PRODUCTS = {
  PAY_IN_3: "payIn3",
  PAY_IN_4: "payIn4",
  PAYLATER: "paylater",
  CREDIT: "credit",
} as const;
